### ISSUE TITLE
Two Horizontal Scroll Bars on Download Page

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#443] opened 2018-11-27 01:09 UTC
![screen shot 2018-11-26 at 8 09 07 pm](https://user-images.githubusercontent.com/139987/49051760-2fea6600-f1b7-11e8-890e-8e49e038ba61.png)

**Comment by arielsvn** [comment] 2019-02-18 21:25
We deployed several updates that changed the structure of the samples table. @Miserlou can you check if you still get this error? I tested locally with FF couldn't reproduce it.

**Comment by arielsvn** [comment] 2019-03-04 15:18
Gonna close this, feel free to re-open if you notice this again.

**Closed by arielsvn** 2019-03-04 15:18 UTC
Labels: bug, next, visual consistency
