### ISSUE TITLE
No Methods To Clear Dataset

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#120] opened 2018-07-05 22:40 UTC
I have an active dataset. I want to start a new dataset. There is no way to do this.

**Comment by Miserlou** [comment] 2018-07-16 16:12
Dupe of https://github.com/AlexsLemonade/refinebio-frontend/issues/102

**Comment by dongbohu** [comment] 2018-07-19 18:20
Closed because it is a duplicate of #102.

**Closed by dongbohu** 2018-07-19 18:20 UTC
Labels: duplicate, mvp, new-feature
