### ISSUE TITLE
Add All Results To Dataset Button

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#487] opened 2019-01-09 22:15 UTC
I'm actually trying to build a dataset right now and it's super annoying to have to go to each page to get the results.

<img width="648" alt="screen shot 2019-01-09 at 5 14 23 pm" src="https://user-images.githubusercontent.com/139987/50931938-1bde8900-1432-11e9-9d4d-667698b8c437.png">

Please give me an Add All Results button

**Comment by arielsvn** [comment] 2019-01-10 15:17
I asked @dvenprasad about this. This friction is by design, we want people to choose what experiments they want in a dataset. Does the species compendia helps for this use case?

**Comment by Miserlou** [comment] 2019-01-10 15:30
I'd rather sort that out once I've got the data rather than slog through the web service though, especially when there are so many pages. I just want the data.

I don't see how "Add Page To Dataset", right at the top, is any less frictional than "Add All To Dataset", it's just far more tedious.

**Comment by cgreene** [comment] 2019-01-10 15:42
This may be a case where your use case would be solved by the compendia, and the users who are searching for specific data would want to see the details about the datasets that they are adding.

On the computational side, I can think of use cases where someone would want all data and others where someone wants specific datasets, but I can't think of a case where I'd want to grab all the results of some search without looking at the results. The closest thing I can imagine is someone who searches for their own author name and wants to download all datasets attributed to them, but I still think they would scan through the list.

**Comment by cgreene** [comment] 2019-01-10 15:43
I guess a follow-up question for you is: were all of the datasets that you searched for _actually_ osteosarcoma data? If the search is that good then I can see a case where a user would want to download all data for a specific disease.

**Comment by Miserlou** [comment] 2019-01-10 15:54
The majority were, it got worse as the results went on, as there were some for osteoarthritis, and some which I [can't explain their inclusion](https://www.refine.bio/experiments/GSE16070). I imagine I'd remove those at the review step, as that's why we have it.

I just don't see any scenario that somebody is going to press Add Page to Dataset without wanting to add all, since that button only appears at the top, before any search results are returned.

You can also get fairly close to the functionality just by changing the number of experiments returned and pressing Add Page. (This also breaks the pagination at the bottom, which I'll open another ticket for.)

**Comment by cgreene** [comment] 2019-01-10 15:56
I guess that I also am not really sure that the Add Page to Dataset button addresses a need. I imagine most users adding individual datasets as they quickly review them. I'll agree that if there is a use case that that button serves, and Add All may serve it just as well.

**Comment by dvenprasad** [comment] 2019-02-14 16:22
When we designed the page, we decided that users will not be able to add all the search results, and if they wanted all data, they would have to use the species compendia. 

If someone downloaded all the data via the WebUI, they will receive something that is smashed differently than the species compendia. Will that still work for this use case?

**Comment by cgreene** [comment] 2019-02-14 16:27
If someone downloads all the data via the WebUI they will get a worse answer than the species compendium (which has helpful but computationally costly imputation steps built in).

**Comment by arielsvn** [comment] 2019-07-01 19:58
I'm going to close this, we can reopen if we get to implement it later.

**Closed by arielsvn** 2019-07-01 19:58 UTC
Labels: backlog
